services:
  tic-db:
    image: postgres:15-alpine
    container_name: tic-db
    environment:
      POSTGRES_USER: tic_user
      POSTGRES_PASSWORD: tic_password
      POSTGRES_DB: tic_data
    ports:
      - "5432:5432"
    volumes:
      - ./src/etl_db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tic_user -d tic_data"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  tic-etl:
    build:
      context: .
      dockerfile: src/etl_db/Dockerfile
    container_name: tic-etl
    restart: always
    env_file:
      - ./secrets/etl.env
    depends_on:
      tic-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://tic_user:tic_password@tic-db:5432/tic_data

  pod-one:
    build:
      context: .
      dockerfile: src/engine_py/Dockerfile
    container_name: pod-one
    restart: unless-stopped
    env_file:
      - ./secrets/strat_one.env
    depends_on:
      tic-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://tic_user:tic_password@tic-db:5432/tic_data
      - CONFIG_PATH=/app/config.yaml 
    volumes:
      - ./src/engine_py/src/strategy/example_strat/config.yaml:/app/config.yaml

  pod-two:
    build:
      context: .
      dockerfile: src/engine_py/Dockerfile
    container_name: pod-two
    restart: unless-stopped
    env_file:
      - ./secrets/strat_two.env
    depends_on:
      tic-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://tic_user:tic_password@tic-db:5432/tic_data
      - CONFIG_PATH=/app/config.yaml 
    volumes:
      - ./src/engine_py/src/strategy/example_strat_two/config.yaml:/app/config.yaml