strategy:
  name: "RSI"
  timeframe: "1h"
  params:
    period: 14
    overbought: 70
    oversold: 30
    trend_period: 250
assets:
  - BTC-USD
  - ETH-USD
  - XRP-USD
  - BNB-USD
  - SOL-USD
  - HYPE-USD
  - TRX-USD
  - DOGE-USD
  - LEO-USD
  - BCH-USD




# Execution Configuration
execution:
  type: "mock"
  paper: true
