# General Pod Settings
poll_interval_seconds: 60
lookback: 50
assets:
  - AAPL
  - TSLA
  - SPY
  - BTCUSD
  - ETHUSD
  - SOLUSD


# Strategy Configuration
strategy:
  name: "ExampleStrategy"
  timeframe: "1h"
  # trade_every: "1d"  # optional: trade daily using hourly candles
  params:
    sma_window: 20
