from enum import Enum
from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field

# ENUMS
class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"

class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"

# MARKET DATA
class Candle(BaseModel):
    """
    Standardized OHLCV market tick.
    """
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

class MarketData(BaseModel):
    """
    A collection of historical data organized by ticker.
    """
    data: Dict[str, List[Candle]] = Field(default_factory=dict)

    def symbols(self) -> List[str]:
        """Returns a list of all symbols in the market data."""
        return list(self.data.keys())

# SYSTEM STATE
class PortfolioState(BaseModel):
    """
    A snapshot of the trading account's current state.
    """
    cash: float = Field(..., description="Available cash (can be negative if using margin)")
    positions: Dict[str, float] = Field(default_factory=dict, description="Current holdings {symbol: qty}")
    prices: Dict[str, float] = Field(default_factory=dict, description="Latest close prices {symbol: price}")

    @property
    def total_equity(self) -> float:
        """Calculates total value: Cash + (Owned Shares * Current Price)"""
        # Initialize total equity with available cash
        portfolio_value = self.cash
        
        # For each position, add the value of the shares to the total equity
        for symbol, qty in self.positions.items():
            portfolio_value += qty * self.prices.get(symbol, 0.0)

        return portfolio_value


# STRATEGY OUTPUT
class TargetAllocation(BaseModel):
    """
    The output of a Strategy.
    """
    symbol: str
    weight: float = Field(..., ge=0.0, le=1.0, description="Target percentage (0.0 to 1.0)")


# EXECUTION INTENT
class OrderRequest(BaseModel):
    """
    A concrete action to be taken by the broker.
    Generated by the Transformer, vetted by Risk.
    """
    symbol: str
    qty: float = Field(..., gt=0.0, description="Absolute quantity to trade")
    side: OrderSide
    type: OrderType = OrderType.MARKET
    limit_price: Optional[float] = None


# EXECUTION RECEIPT
class TradeReceipt(BaseModel):
    """
    Confirmation of an executed order, returned by the broker.
    """
    broker_order_id: str
    symbol: str
    side: OrderSide
    qty: float
    status: str
    filled_price: Optional[float] = None